# Generated by Django 3.0.1 on 2019-12-25 12:20

from django.db import migrations, models
import django.db.models.deletion
import utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardboardWish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardboard_name', models.CharField(max_length=255)),
                ('minimum_amount', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(default=1)),
                ('wish_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='wishlist.WishList')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('wishlist.fromexpansions', 'from expansions'), ('wishlist.isborder', 'is border'), ('wishlist.isminimumcondition', 'is minimum condition'), ('wishlist.islanguage', 'is language'), ('wishlist.isfoil', 'is foil'), ('wishlist.isaltered', 'is altered'), ('wishlist.issigned', 'is signed')], db_index=True, max_length=255)),
                ('border', utils.fields.EnumField(enum_type='mtgorp.models.persistent.attributes.borders.Border', null=True)),
                ('condition', utils.fields.EnumField(enum_type='wishlist.values.Condition', null=True)),
                ('language', utils.fields.EnumField(enum_type='wishlist.values.Language', null=True)),
                ('is_foil', models.BooleanField(null=True)),
                ('is_altered', models.BooleanField(null=True)),
                ('is_signed', models.BooleanField(null=True)),
                ('cardboard_wish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='wishlist.CardboardWish')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cardboardwish',
            name='wish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardboard_wishes', to='wishlist.Wish'),
        ),
        migrations.CreateModel(
            name='FromExpansions',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wishlist.requirement',),
        ),
        migrations.CreateModel(
            name='IsAltered',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wishlist.requirement',),
        ),
        migrations.CreateModel(
            name='IsBorder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wishlist.requirement',),
        ),
        migrations.CreateModel(
            name='IsFoil',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wishlist.requirement',),
        ),
        migrations.CreateModel(
            name='IsLanguage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wishlist.requirement',),
        ),
        migrations.CreateModel(
            name='IsMinimumCondition',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wishlist.requirement',),
        ),
        migrations.CreateModel(
            name='IsSigned',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wishlist.requirement',),
        ),
    ]
