# Generated by Django 3.1.3 on 2021-05-26 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0020_versionedcube_forked_from_release'),
        ('draft', '0007_draftsession_infinites'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageQtyRecordPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_amount', models.IntegerField()),
                ('average_image_amount', models.FloatField()),
                ('probability', models.FloatField()),
                ('pick', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='image_records', to='draft.draftpick')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booster_image_records', to='api.cuberelease')),
            ],
        ),
        migrations.CreateModel(
            name='DraftChecked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='image_quantity_checks', to='draft.draftsession')),
            ],
        ),
    ]
