version: '3.3'

services:

  db:
    environment:
      DEBUG: 0

  nginx:
    image: nginx:1.13
    ports:
      - "${PORT_OUT}:80"
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ~/.local/share/mtgorp:/opt/services/cubeapp/mtgorp
      - ~/.local/share/mtgimg:/opt/services/cubeapp/mtgimg
      - static_volume:/opt/services/cubeapp/static
      - media_volume:/opt/services/cubeapp/media
    depends_on:
      - web
      - web_channels
    networks:
      - nginx_network
    env_file:
      - .env
    environment:
      DEBUG: 0

  web_channels:
    command: daphne -b 0.0.0.0 -p 7001 cubeapp.asgi:application
    image: app-image
    volumes:
      - .:/code
      - ~/.local/share/mtgimg:/root/.local/share/mtgimg
      - ~/.local/share/mtgorp:/root/.local/share/mtgorp
      - static_volume:/opt/services/cubeapp/static
      - media_volume:/opt/services/cubeapp/media
    restart: on-failure
    depends_on:
      - db
      - redis
    networks:
      - database_network
      - nginx_network
    env_file:
      - .env
    environment:
      DEBUG: 0

  celery_worker:
    environment:
      DEBUG: 0

  celery_beat:
    environment:
      DEBUG: 0

  web:
    networks:
      - nginx_network
    environment:
      DEBUG: 0

  redis:
    environment:
      DEBUG: 0

#  rabbitmq:
#    environment:
#      DEBUG: 0


networks:
  nginx_network:
    driver: bridge