version: '3.3'

services:

  pdb:
    environment:
      DEBUG: 0

  nginx:
    image: nginx:1.13
#    command: nginx -c /etc/config_files/production.conf
    ports:
      - "${PORT_OUT}:80"
      - "443:443"
    volumes:
      - ./nginx/production.conf:/etc/nginx/conf.d/additional.conf
      - ~/.local/share/mtgorp:/opt/services/cubeapp/mtgorp
      - ~/.local/share/mtgimg:/opt/services/cubeapp/mtgimg
      - /home/ftper/ftp/files:/opt/services/cubeapp/files
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/data:/etc/letsencrypt/
      - static_volume:/opt/services/cubeapp/static
      - media_volume:/opt/services/cubeapp/media
    depends_on:
      - web
      - web_channels
    networks:
      - nginx_network
    env_file:
      - .env
    environment:
      DEBUG: 0

  web_channels:
    entrypoint: ./channels_entrypoint.sh
    image: app-image
    volumes:
      - .:/code
      - ./appdirs/:/root/.local/share/
      - ~/.local/share/mtgimg:/root/.local/share/mtgimg
      - ~/.local/share/mtgorp:/root/.local/share/mtgorp
      - static_volume:/opt/services/cubeapp/static
      - media_volume:/opt/services/cubeapp/media
    restart: on-failure
    depends_on:
      - pdb
      - redis
    networks:
      - database_network
      - nginx_network
    env_file:
      - .env
    environment:
      DEBUG: 0

  celery_worker:
    environment:
      DEBUG: 0

  celery_beat:
    environment:
      DEBUG: 0

  web:
    networks:
      - nginx_network
    environment:
      DEBUG: 0

  redis:
    environment:
      DEBUG: 0


networks:
  nginx_network:
    driver: bridge