version: '3.3'

services:
  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/opt/services/cubeapp/static
      - media_volume:/opt/services/cubeapp/meda
    depends_on:
      - web
      - web_channels
    networks:
      - nginx_network

  web_channels:
    command: daphne -b 0.0.0.0 -p 7001 cubeapp.asgi:application
    image: app-image
    volumes:
      - .:/code
      - ~/.local/share/mtgimg:/root/.local/share/mtgimg
      - ~/.local/share/mtgorp:/root/.local/share/mtgorp
      - static_volume:/opt/services/cubeapp/static
      - media_volume:/opt/services/cubeapp/meda
    restart: on-failure
    depends_on:
      - db
      - redis
    networks:
      - database_network
      - nginx_network
    env_file:
      - .env
    environment:
      - DEBUG=0
    ports:
      - 7001:7001

  celery_worker:
    environment:
      - DEBUG=0

  web:
    networks:
      - nginx_network
    environment:
      - DEBUG=0


networks:
  nginx_network:
    driver: bridge