version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'cubespoiler'
      MYSQL_USER: 'phdk'
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - db:/var/lib/docker_mysql
    networks:
      - database_network

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - database_network
    ports:
      - 6379:6379

  celery_worker:
    image: app-image
    command: celery -A cubeapp worker --loglevel=info
    volumes:
      - .:/code
      - ~/.local/share/mtgimg:/root/.local/share/mtgimg
      - ~/.local/share/mtgorp:/root/.local/share/mtgorp
      - static_volume:/opt/services/cubeapp/static
      - media_volume:/opt/services/cubeapp/meda
    depends_on:
      - redis
      - db
    networks:
      - database_network
    restart: on-failure
    env_file:
      - .env

  web:
    build: .
    image: app-image
    volumes:
      - .:/code
      - ~/.local/share/mtgimg:/root/.local/share/mtgimg
      - ~/.local/share/mtgorp:/root/.local/share/mtgorp
      - static_volume:/opt/services/cubeapp/static
      - media_volume:/opt/services/cubeapp/meda
    depends_on:
      - db
      - redis
    networks:
      #      - nginx_network
      - database_network
    env_file:
      - .env

    ports:
      - "7000:7000"

#  nginx:
#    image: nginx:1.13
#    ports:
#      - "${PORT_OUT}:80"
#    volumes:
#      - ./config/nginx/conf.d:/etc/nginx/conf.d
#      - static_volume:/opt/services/cubeapp/static
#      - media_volume:/opt/services/cubeapp/meda
#    depends_on:
#      - web
#    networks:
#      - nginx_network

networks:
  nginx_network:
    driver: bridge
  database_network:
    driver: bridge

volumes:
  db:
  static_volume:
  media_volume:
