version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'cubespoiler'
      MYSQL_USER: 'phdk'
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      DEBUG: 1
    volumes:
      - db:/var/lib/mysql
    networks:
      - database_network

  #  rabbitmq:
  #    image: 'bitnami/rabbitmq:latest'
  #    networks:
  #      - database_network
  #    restart: always
  #    environment:
  #      DEBUG: 1
  #    env_file:
  #      - .env
  #    ports:
  #      - 1515:15672

  redis:
    image: 'bitnami/redis:latest'
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      DEBUG: 1
    networks:
      - database_network
    restart: always

  web:
    build: .
    image: app-image
    restart: always
    volumes:
      - .:/code
      - ~/.local/share/mtgimg:/root/.local/share/mtgimg
      - ~/.local/share/mtgorp:/root/.local/share/mtgorp
      - static_volume:/opt/services/cubeapp/static
      - media_volume:/opt/services/cubeapp/meda
    depends_on:
      - db
      - redis
    networks:
      - database_network
    env_file:
      - .env
    environment:
      - DEBUG=1

  celery_worker:
    image: app-image
    command: celery -A cubeapp worker --loglevel=INFO
    volumes:
      - .:/code
      - ~/.local/share/mtgimg:/root/.local/share/mtgimg
      - ~/.local/share/mtgorp:/root/.local/share/mtgorp
      - static_volume:/opt/services/cubeapp/static
      - media_volume:/opt/services/cubeapp/meda
    depends_on:
      - redis
      - db
    networks:
      - database_network
    restart: always
    env_file:
      - .env
    environment:
      - DEBUG=1

  celery_beat:
    image: app-image
    command: celery -A cubeapp beat --loglevel=INFO
    volumes:
      - .:/code
      - ~/.local/share/mtgimg:/root/.local/share/mtgimg
      - ~/.local/share/mtgorp:/root/.local/share/mtgorp
      - static_volume:/opt/services/cubeapp/static
      - media_volume:/opt/services/cubeapp/meda
    depends_on:
      - redis
      - db
    networks:
      - database_network
    restart: always
    env_file:
      - .env
    environment:
      - DEBUG=1

networks:
  database_network:
    driver: bridge

volumes:
  db:
  static_volume:
  media_volume:
