# Generated by Django 3.0.2 on 2020-02-07 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sealed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='sealed.SealedSession'),
            preserve_default=False,
        ),
    ]
