# Generated by Django 3.0.2 on 2020-02-12 10:27

import api.fields.orp
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sealed', '0002_pool_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='sealedsession',
            name='format',
            field=models.CharField(default='sealed', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PoolDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deck', api.fields.orp.OrpField(model_type='mtgorp.models.collections.deck.Deck')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='sealed.Pool')),
            ],
        ),
    ]
