# Generated by Django 3.0.2 on 2020-02-13 15:42

from django.db import migrations, models
import utils.methods


class Migration(migrations.Migration):

    dependencies = [
        ('sealed', '0004_auto_20200212_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='key',
        ),
        migrations.AddField(
            model_name='pooldeck',
            name='name',
            field=models.CharField(default='deck', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sealedsession',
            name='name',
            field=models.CharField(default=utils.methods.get_random_name, max_length=255),
        ),
    ]
