# Generated by Django 3.0.3 on 2020-02-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealed', '0006_auto_20200222_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='sealedsession',
            name='allow_pool_intersection',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sealedsession',
            name='open_decks',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
