# Generated by Django 3.0.4 on 2020-03-13 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftpick',
            name='drafter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='draft.DraftParticipant'),
        ),
    ]
