# Generated by Django 3.0.4 on 2020-03-24 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('limited', '0005_auto_20200324_1150'),
        ('draft', '0002_auto_20200313_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftsession',
            name='limited_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_session', to='limited.LimitedSession'),
        ),
    ]
