# Generated by Django 3.0.4 on 2020-04-06 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('draft', '0004_auto_20200327_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draftseat',
            options={'ordering': ['sequence_number']},
        ),
        migrations.AlterField(
            model_name='draftseat',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='draft.DraftSession'),
        ),
        migrations.AlterField(
            model_name='draftseat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seats', to=settings.AUTH_USER_MODEL),
        ),
    ]
