# Generated by Django 3.0.7 on 2020-06-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("draft", "0005_auto_20200406_1253"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftsession",
            name="reverse",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
