# Generated by Django 3.1.3 on 2021-06-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("draft", "0008_draftpick_global_pick_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draftpick",
            name="global_pick_number",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
