# Generated by Django 3.1.3 on 2021-09-13 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0010_draftpick_booster_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='draftpick',
            unique_together={('seat', 'pack_number', 'pick_number'), ('booster_id', 'pick_number'), ('seat', 'global_pick_number')},
        ),
    ]
