# Generated by Django 3.1.3 on 2021-12-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("draft", "0011_auto_20210913_1341"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftsession",
            name="time_control",
            field=models.FloatField(null=True),
        ),
    ]
