# Generated by Django 2.2.3 on 2019-07-09 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionedCube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CubeRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('checksum', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=64)),
                ('intended_size', models.PositiveIntegerField()),
                ('cube_content', models.TextField()),
                ('versioned_cube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='api.VersionedCube')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CubeDelta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('versioned_cube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deltas', to='api.VersionedCube')),
            ],
        ),
        migrations.CreateModel(
            name='ConstrainedNodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constrained_nodes_content', models.TextField()),
                ('release', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='constrained_node', to='api.CubeRelease')),
            ],
        ),
    ]
