# Generated by Django 2.2.3 on 2019-07-04 14:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CubeRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('checksum', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=64)),
                ('intended_size', models.PositiveIntegerField()),
                ('cube_content', models.TextField()),
                ('versioned_cube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='api.VersionedCube')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.DeleteModel(
            name='CubeContainer',
        ),
    ]
