# Generated by Django 2.2.5 on 2019-09-20 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='distributionpossibility',
            unique_together={('patch', 'patch_checksum', 'distribution_checksum')},
        ),
    ]
