# Generated by Django 2.2.3 on 2019-07-09 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constrainednodes',
            name='release',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='constrained_nodes', to='api.CubeRelease'),
        ),
    ]
