# Generated by Django 2.2.5 on 2019-10-07 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190920_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuberelease',
            old_name='cube_content',
            new_name='cube',
        ),
    ]
