# Generated by Django 2.2.3 on 2019-07-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190709_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='cubedelta',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
