# Generated by Django 2.2.3 on 2019-07-03 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190528_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionedCube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
    ]
