# Generated by Django 2.2.5 on 2019-10-07 09:45

from django.db import migrations

import api.fields.orp


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_auto_20191007_0944"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuberelease",
            name="cube",
            field=api.fields.orp.OrpField(model_type="magiccube.collections.cube.Cube"),
        ),
    ]
