# Generated by Django 2.2.4 on 2019-08-02 11:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_cubedelta_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CubeDelta',
            new_name='CubePatch',
        ),
    ]
