# Generated by Django 2.2.5 on 2019-10-07 09:45

import api.fields.orp
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191007_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuberelease',
            name='cube',
            field=api.fields.orp.OrpField(model_type='magiccube.collections.cube.Cube'),
        ),
    ]
