# Generated by Django 2.2.5 on 2019-10-07 14:37

import api.fields.orp
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20191007_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionpossibility',
            name='trap_collection',
            field=api.fields.orp.OrpField(model_type='magiccube.collections.laps.TrapCollection'),
        ),
    ]
