# Generated by Django 2.2.7 on 2019-11-26 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0011_auto_20191007_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name = 'distributionpossibility',
            name = 'release',
            field = models.ForeignKey(
                default = 1,
                on_delete = django.db.models.deletion.CASCADE,
                to = 'api.CubeRelease',
            ),
            preserve_default = False,
        ),

    ]
