# Generated by Django 3.0.4 on 2020-04-06 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_auto_20191126_1452"),
    ]

    operations = [
        migrations.AddField(
            model_name="versionedcube",
            name="active",
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name="versionedcube",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versionedcube",
            name="forked_from",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="forks", to="api.VersionedCube"
            ),
        ),
    ]
