# Generated by Django 3.0.8 on 2020-07-22 09:29

import api.fields.orp
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200602_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuberelease',
            name='infinites',
            field=api.fields.orp.OrpField(
                default={"cardboards": ["Plains", "Forest", "Mountain", "Swamp", "Island", "Wastes"]},
                model_type='magiccube.collections.infinites.Infinites',
            ),
            preserve_default=False,
        ),
    ]
