# Generated by Django 3.1.3 on 2021-03-17 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_auto_20201214_1520"),
    ]

    operations = [
        migrations.AddField(
            model_name="versionedcube",
            name="forked_from_release",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="forks", to="api.cuberelease"
            ),
        ),
    ]
