# Generated by Django 3.1.3 on 2021-09-16 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0021_expansionupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedPrinting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printing_id', models.PositiveIntegerField()),
                ('related_object_id', models.PositiveIntegerField()),
                ('related_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'unique_together': {('printing_id', 'related_content_type', 'related_object_id')},
            },
        ),
    ]
