# Generated by Django 3.2.25 on 2025-10-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_versionedcube_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedprinting',
            name='printing_id',
            field=models.BigIntegerField(),
        ),
    ]
