# Generated by Django 3.1.2 on 2020-10-01 10:26

import api.fields.orp
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardboardCubeableRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardboard_cubeable_id', models.CharField(max_length=2047)),
                ('cardboard_cubeable', api.fields.orp.CardboardCubeableField()),
                ('rating', models.PositiveSmallIntegerField()),
                ('rating_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='rating.ratingmap')),
            ],
        ),
        migrations.DeleteModel(
            name='CubeableRating',
        ),
    ]
