# Generated by Django 3.1.3 on 2021-03-02 10:37

from django.db import migrations

import api.fields.orp


class Migration(migrations.Migration):
    dependencies = [
        ("rating", "0003_auto_20210226_1111"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cardboardcubeablerating",
            options={"ordering": ("-rating",)},
        ),
        migrations.AddField(
            model_name="cardboardcubeablerating",
            name="example_cubeable",
            field=api.fields.orp.CubeableField(default=None),
            preserve_default=False,
        ),
    ]
