# Generated by Django 3.1.3 on 2021-03-17 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rating", "0004_auto_20210302_1037"),
    ]

    operations = [
        migrations.AddField(
            model_name="ratingmap",
            name="parent",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="children", to="rating.ratingmap"
            ),
        ),
    ]
