# Generated by Django 3.1.3 on 2021-06-07 13:52

import api.fields.orp
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0008_noderatingcomponent_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardboardStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardboard', api.fields.orp.CardboardField()),
                ('pool_occurrences', models.FloatField()),
                ('maindeck_occurrences', models.FloatField()),
                ('sideboard_occurrences', models.FloatField()),
                ('real_sideboard_occurrences', models.IntegerField()),
                ('maindeck_matches', models.FloatField()),
                ('real_maindeck_matches', models.IntegerField()),
                ('sideboard_matches', models.FloatField()),
                ('real_sideboard_matches', models.IntegerField()),
                ('maindeck_wins', models.FloatField()),
                ('real_maindeck_wins', models.IntegerField()),
                ('sideboard_wins', models.FloatField()),
                ('real_sideboard_wins', models.IntegerField()),
                ('deck_occurrences', models.FloatField()),
                ('real_deck_occurrences', models.IntegerField()),
                ('deck_conversion_rate', models.FloatField()),
                ('ci_deck_conversion_rate', models.FloatField()),
                ('maindeck_conversion_rate', models.FloatField()),
                ('ci_maindeck_conversion_rate', models.FloatField()),
                ('sideboard_conversion_rate', models.FloatField()),
                ('ci_sideboard_conversion_rate', models.FloatField()),
                ('matches', models.FloatField()),
                ('real_matches', models.IntegerField()),
                ('wins', models.FloatField()),
                ('real_wins', models.IntegerField()),
                ('win_rate', models.FloatField()),
                ('ci_win_rate', models.FloatField()),
                ('maindeck_win_rate', models.FloatField()),
                ('ci_maindeck_win_rate', models.FloatField()),
                ('sideboard_win_rate', models.FloatField()),
                ('ci_sideboard_win_rate', models.FloatField()),
                ('rating_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardboard_statistics', to='rating.ratingmap')),
            ],
            options={
                'unique_together': {('cardboard', 'rating_map')},
            },
        ),
    ]
