# Generated by Django 3.1.3 on 2021-11-15 13:17

import api.fields.orp
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0009_cardboardstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardboardStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardboard', api.fields.orp.CardboardField()),
                ('stat', models.CharField(max_length=63)),
                ('value', models.FloatField()),
                ('rating_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardboard_statistics', to='rating.ratingmap')),
            ],
            options={
                'unique_together': {('cardboard', 'rating_map', 'stat')},
            },
        ),
        migrations.DeleteModel(
            name='CardboardStats',
        ),
    ]
