# Generated by Django 3.1.3 on 2020-12-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentparticipant',
            name='seed',
            field=models.FloatField(default=0.0),
        ),
    ]
