# Generated by Django 3.1.3 on 2020-12-18 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_auto_20201218_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentparticipant',
            options={'ordering': ('-seed',)},
        ),
        migrations.AddField(
            model_name='tournament',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='draws',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scheduledseat',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tournament_seats', to='tournaments.tournamentparticipant'),
        ),
        migrations.AlterField(
            model_name='tournamentwinner',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='tournaments.tournamentparticipant'),
        ),
    ]
