# Generated by Django 3.1.3 on 2021-02-18 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("limited", "0019_pooldeck_latest"),
        ("tournaments", "0004_auto_20201218_1548"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentparticipant",
            name="placement",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="tournamentparticipant",
            name="deck",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="tournament_entries", to="limited.pooldeck"
            ),
        ),
        migrations.AlterField(
            model_name="tournamentparticipant",
            name="player",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tournament",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
