# Generated by Django 3.1.3 on 2020-12-30 10:10

import django.db.models.deletion
from django.db import migrations, models
from mtgorp.models.tournaments.tournaments import Tournament

import utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("api", "0019_auto_20201214_1520"),
        ("tournaments", "0004_auto_20201218_1548"),
    ]

    operations = [
        migrations.CreateModel(
            name="HOFLeague",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("previous_n_releases", models.PositiveSmallIntegerField()),
                ("season_size", models.PositiveSmallIntegerField()),
                ("top_n_from_previous_season", models.PositiveSmallIntegerField()),
                ("low_participation_prioritization_amount", models.PositiveSmallIntegerField()),
                ("tournament_type", utils.fields.StringMapField(mapping=Tournament.tournaments_map, max_length=255)),
                ("tournament_config", models.JSONField()),
                ("match_type", utils.fields.SerializeableField(klass="mtgorp.models.tournaments.matches.MatchType")),
                (
                    "versioned_cube",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="leagues", to="api.versionedcube"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="seasons", to="league.hofleague"
                    ),
                ),
                (
                    "tournament",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="season", to="tournaments.tournament"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
