# Generated by Django 3.1.3 on 2021-02-25 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('limited', '0019_pooldeck_latest'),
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='ratings_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ParticipantRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_ratings', to='limited.pooldeck')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='league.hofleague')),
            ],
        ),
    ]
