# Generated by Django 3.1.3 on 2021-04-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("league", "0003_auto_20210225_1038"),
    ]

    operations = [
        migrations.AddField(
            model_name="hofleague",
            name="rating_change",
            field=models.PositiveSmallIntegerField(default=64),
            preserve_default=False,
        ),
    ]
