# Generated by Django 3.1.3 on 2021-06-07 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_auto_20210218_1205'),
        ('league', '0004_hofleague_rating_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ratings_processed', models.BooleanField(default=False)),
                ('rated', models.BooleanField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_matches', to='league.hofleague')),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quick_match', to='tournaments.tournament')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
