# Generated by Django 3.1.3 on 2021-06-08 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('league', '0005_quickmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickmatch',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='created_quick_matches', to='auth.user'),
            preserve_default=False,
        ),
    ]
