# Generated by Django 3.1.3 on 2021-09-24 12:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="forecastslicesnapshot",
            old_name="from_time",
            new_name="start_time",
        ),
    ]
