# Generated by Django 3.0.3 on 2020-03-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("limited", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="boosterspecification",
            name="amount",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="boosterspecification",
            name="sequence_number",
            field=models.IntegerField(default=0),
        ),
    ]
