# Generated by Django 3.0.4 on 2020-03-24 11:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('limited', '0004_matchplayer_matchresult'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchplayer',
            unique_together={('user', 'match_result')},
        ),
    ]
