# Generated by Django 3.0.5 on 2020-04-13 12:46

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import IntegerField


class Migration(migrations.Migration):

    dependencies = [
        ('limited', '0005_auto_20200324_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitedsession',
            name='information_level',
            field=IntegerField(default = 0),
        ),
        migrations.RunSQL(
            """
            UPDATE limited_limitedsession SET information_level = 1 WHERE open_decks = true;
            """
        ),
        migrations.RunSQL(
            """
            UPDATE limited_limitedsession SET information_level = 0 WHERE open_decks = false;
            """
        ),
        migrations.RemoveField(
            model_name = 'limitedsession',
            name = 'open_decks',
        ),
        migrations.AlterField(
            model_name='pooldeck',
            name='pool',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deck', to='limited.Pool'),
        ),
    ]
