# Generated by Django 3.0.5 on 2020-04-13 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("limited", "0006_auto_20200413_1246"),
    ]

    operations = [
        migrations.AddField(
            model_name="limitedsession",
            name="open_decks",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="limitedsession",
            name="open_pools",
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL(
            """
            UPDATE limited_limitedsession SET open_decks = true WHERE information_level = 1;
            """
        ),
        migrations.RunSQL(
            """
            UPDATE limited_limitedsession SET open_decks = false WHERE information_level = 0;
            """
        ),
        migrations.RemoveField(
            model_name="limitedsession",
            name="information_level",
        ),
        migrations.AlterField(
            model_name="pooldeck",
            name="pool",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="pool_deck", to="limited.Pool"
            ),
        ),
    ]
