# Generated by Django 3.0.8 on 2020-07-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("limited", "0008_limitedsession_infinites"),
    ]

    operations = [
        migrations.AddField(
            model_name="boosterspecification",
            name="scale",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
