# Generated by Django 3.1.3 on 2020-12-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limited', '0011_poolsharingcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitedsession',
            name='allow_cheating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pooldeck',
            name='cheating',
            field=models.BooleanField(default=False),
        ),
    ]
