# Generated by Django 3.1.3 on 2020-12-02 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('limited', '0012_auto_20201202_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pooldeck',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_decks', to='limited.pool'),
        ),
    ]
