# Generated by Django 3.1.3 on 2020-12-14 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('limited', '0013_auto_20201202_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pooldeck',
            options={'ordering': ('created_at',)},
        ),
    ]
