# Generated by Django 3.1.3 on 2020-12-18 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0002_tournamentparticipant_seed"),
        ("limited", "0015_limitedsession_tournament"),
    ]

    operations = [
        migrations.AlterField(
            model_name="limitedsession",
            name="tournament",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tournament",
                to="tournaments.tournament",
            ),
        ),
    ]
