# Generated by Django 3.1.3 on 2020-12-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limited', '0018_auto_20201220_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='pooldeck',
            name='latest',
            field=models.BooleanField(default=True),
        ),
    ]
