# Generated by Django 3.1.3 on 2021-09-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kpd", "0004_auto_20210928_1313"),
    ]

    operations = [
        migrations.AddField(
            model_name="logpoint",
            name="type",
            field=models.CharField(default="kebab", max_length=31),
            preserve_default=False,
        ),
    ]
